config/routes.rb
Rails.application.routes.draw do

  root 'top#index'
  get "users" => "users#index"
  get 'index' => 'index#index'
  get "/user_identifications/new" => "user_identifications#new"
  post "/user_identifications/new" => "user_identifications#create"
  # View作成用無理やりルーティング。あとで消す。kajitani
  get "users/destroy"

  devise_scope :user do
    post 'users', to: 'devise/registrations#create'
  end
  devise_for :users

  resources :users, only: [:edit, :show, :update]

  resources :signups, only: [:index] do
    collection do
      get 'step1'   
      post 'step1', to: 'signups#step1_validates' 
      get 'step2'  
      post 'step2', to: 'signups#step2' 
      resource :phones,only: [:new] do
        collection do
      post 'step3', to: "signups#step3"
      get  "step4_new", to: "signups#step4_new"
      post "step4", to: "signups#step4"
       end
      end
    end   
  end    

  resources :credit_cards, only: [:new, :show] do
    collection do
      post 'show', to:   'credit_cards#show'
      post 'pay', to:    'credit_cards#pay'
      post 'delete', to: 'credit_cards#delete'
    end
  end

  resources :products do
    member do
      get :purchase
      post :pay, to: "products#pay"
    end

    collection do
      get "cate_children" 
      get "grand_children" 
      get 'top/search'
    end

    resources :likes, only: [:create]
  end
  
  resources :comments, only: [:index, :create] 

end

app/models/address.rb
class Address < ActiveHash::Base
  self.data = [
    {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
    {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
    {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
    {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
    {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
    {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
    {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
    {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
    {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
    {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
    {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
    {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
    {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
    {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
    {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
    {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'},{id: 48, name: '未定'}
]
end

app/models/category.rb
class Category < ApplicationRecord
  has_ancestry
  has_many :products
end

app/models/charge.rb
class Charge < ApplicationRecord
end

app/models/charge_method.rb
class ChargeMethod < ApplicationRecord
  has_many :products
  has_ancestry
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  belongs_to :user

  validates :content, presence: true
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
  has_many :products
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/moredit_card.rb
class MoreditCard < ApplicationRecord
end

app/models/period.rb
class Period < ApplicationRecord
  has_ancestry
  has_many :products
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :user
  validates :number, presence: true
  validates :comfirm_number, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  
  belongs_to :user
  belongs_to :category, optional: true
  belongs_to :period,   optional: true
  belongs_to :charge_method, optional: true

  has_many  :product_images
  accepts_nested_attributes_for :product_images

  belongs_to_active_hash :address
  belongs_to_active_hash :status
  belongs_to_active_hash :period
  belongs_to_active_hash :size

  def previous
    Product.where("id < ?", self.id).order("id DESC").first
  end
 
  def next
    Product.where("id > ?", self.id).order("id ASC").first
  end
end

app/models/send_area.rb
class SendArea < ApplicationRecord
  belongs_to :products ,optional: true
end

app/models/send_method.rb
class SendMethod < ActiveHash::Base
end

app/models/sendmethod.rb
class Sendmethod < ActiveHash::Base
  self.data = [
    {id: 1, name: '未定'}, {id: 2, name: 'らくらくメルカリ便'}, {id: 3, name: 'ゆうメール'},
    {id: 4, name: 'レターパック'}, {id: 5, name: '普通郵便(定形、定形外)'}, {id: 6, name: 'クロネコヤマト'},
    {id: 7, name: 'ゆうパック'}, {id: 8, name: 'クリックポスト'}, {id: 9, name: 'ゆうパケット'}
]
end

app/models/size.rb
class Size < ActiveHash::Base
  self.data = [
    {id: 1, size: 'XXS以下'}, {id: 2, size: 'XS(SS)'}, {id: 3, size: 'S'},
    {id: 4, size: 'M'}, {id: 5, size: 'L'}, {id: 6, size: 'XL(LL)'},
    {id: 7, size: '2XL(3L)'}, {id: 8, size: '3XL(4L)'}, {id: 9, size: '4XL(5L)以上'},
    {id: 10, size: 'FREE SIZE'}
]
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
    {id: 1, status: '新品、未使用'}, {id: 2, status: '未使用に近い'}, {id: 3, status: '目立った傷や汚れなし'},
    {id: 4, status: 'やや傷や汚れあり'}, {id: 5, status: '傷や汚れあり'}, {id: 6, status: '全体的に状態が悪い'}
]
end

app/models/user.rb
class User < ApplicationRecord
  has_one :phone
  accepts_nested_attributes_for :phone

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         number = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{7,100}+\z/i
         validates :password, presence: true,length: { minimum: 7 }  , format: { with: number }
         validates :lastname, presence: true
         validates :firstname, presence: true
         validates :firstname_kana, presence: true
         validates :lastname_kana, presence: true
         validates :birthday, presence: true
         validates :email, presence: true
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @products = Product.limit(10)
    @q = Product.ransack(params[:q])
    @result = @q.result(distinct: true)

    @ladies = Product.where(category_id: 1..207).limit(10)
    @mens = Product.where(category_id: 208..353).limit(10)
    @electricals = Product.where(category_id: 903..988).limit(10)
    @toys = Product.where(category_id: 690..802).limit(10)
  end
  def search
    @q = Product.ransack(params[:q])
    @result = @q.result.page(params[:page]).per(132)
    render "top/search"
  end

end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/top/_advertisement-bar.html.haml
-# 後日修正のためのメモ書き
-# .content__main--advertisement_bar__box
-#   = link_to "test", rel: "noopener noreferrer", target: "_blank" do
-#     = image_tag 'https://web-jp-assets.mercdn.net/_next/static/images/top-banner-kaushika-8f6ea67….jpg', alt: '', class: 'content__main--advertisement_bar__box--link'
-#     -# .content__main--advertisement_bar__box--link
-#   .content__main--advertisement_bar__box--details
-#     .slider-frame
-#       %ul.slider-list
-#         %li.slider-slide
-#           = link_to "https://jp-news.mercari.com/2019/12/05/kaushika-kaudake", rel: "noopener noreferrer", target: "_blank" do
-#             .content__main--advertisement_bar__box--details__specific{"aria-hidden": "true"}
-#         %li.slider-slide.camp
-#           = link_to "https://www.mercari.com/jp/featured/camp/" do
-#             .content__main--advertisement_bar__box--details__specific{"aria-hidden": "true"}
-#         %li.slider-slide.slide-visible
-#           .content__main--advertisement_bar__box--details__specific
-#             .content__main--advertisement_bar__box--details__specific--pic_element
-#               = image_tag "https://web-jp-assets.mercdn.net/_next/static/images/top-banner-main-device-1f627e51e488f6ca35feaa6a08b79736.png", alt: "", class: "content__main--advertisement_bar__box--details__specific--pic_element__picture"
-#               .content__main--advertisement_bar__box--details__specific--pic_element__font_area
-#                 .content__main--advertisement_bar__box--details__specific--pic_element__font_area--upper
-#                   スマホで かんたん
-#                   %br/
-#                   フリマアプリ
-#                 %p.content__main--advertisement_bar__box--details__specific--pic_element__font_area--middle
-#                   メルカリはスマホカメラからすぐに出品できる
-#                   %br/
-#                   購入時も安心な独自システムのアプリです
-#                 .content__main--advertisement_bar__box--details__specific--pic_element__font_area--lower
-#                   = link_to "https://itunes.apple.com/jp/app/id667861049?l=ja&mt=8", rel: "noopener noreferrer", target: "_blank" do
-#                     = image_tag "https://web-jp-assets.mercdn.net/_next/static/images/app-store-a5c17948c6fd6d5b60b13d421cd60b35.svg", alt: "", class: "content__main--advertisement_bar__box--details__specific--pic_element__font_area--lower__icons"
-#                   = link_to "https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja", rel: "noopener noreferrer", target: "_blank" do
-#                     = image_tag "https://web-jp-assets.mercdn.net/_next/static/images/google-play-495575abb895b405aa6336b2a4304958.svg", alt: "", class: "content__main--advertisement_bar__box--details__specific--pic_element__font_area--lower__icons"
-#     .slider-control-centerleft
-#       .content__main--advertisement_bar__box--details--arrow.left
-#     .slider-control-centerright
-#       .content__main--advertisement_bar__box--details--arrow.right
-#     .slider-control-bottomcenter
-#       .style_dotsIndicator__1fZnt.common_fontFamily__3-3Si.style_center__2IkR_.style_mono__3e12j.sc-iGPElx.zxiXZ
-#         %span
-#         %span
-#         %span.style_active__2ihlK
-#     :css
-#       .slider-slide > img { width: 100%; display: block; }
-#                 .slider-slide > img:focus { margin: auto; }
/
  <a href="test">
  <div class="content__main--advertisement_bar__box">
  </div>
  </a>
  <div class="content__main--advertisement_bar__sample_view">
  </div>

.slider
  -# .slider-list
  %li
    = image_tag "banner-1.png"
  %li
    = image_tag "banner-2.jpg"

app/views/top/_download-bar.html.haml
.download-bar__aside
  = link_to "test", class: "download-bar__aside--box" do
    = image_tag "mercari-icon.png", class: "download-bar__aside--box__icon"
    .download-bar__aside--box__text
      スマホでかんたんフリマアプリ
      .download-bar__aside--box__text--lower
        今すぐ無料ダウンロード
.download-bar__show
  .download-bar__show--box
    .download-bar__show--box__left
      .download-bar__show--box__left--upper
        スマホでかんたんフリマアプリ
      .download-bar__show--box__left--middle
        今すぐ無料ダウンロード
      .download-bar__show--box__left--lower
        = image_tag "mercari-icon.png", alt: "", class: "download-bar__show--box__left--lower__mercari-icon"
        = link_to "test", class: "download-bar__show--box__left--lower__link", target: "_blank" do
          = image_tag "app-store.svg", alt: "", class: "download-bar__show--box__left--lower__link--icon"
        = link_to "test", class: "download-bar__show--box__left--lower__link", target: "_blank" do
          = image_tag "google-play.svg", alt: "", class: "download-bar__show--box__left--lower__link--icon"
    %figure.download-bar__show--box__right
      = image_tag "download_app_pc.png", alt: "", class: "download-bar__show--box__right--pic"

app/views/top/_footer.html.haml
%nav.footer__details
  .footer__details--box
    %h2.footer__details--box__title
      メルカリについて
    .footer__details--box__letters
      %ul.footer__details--box__letters--area
        %li.footer__details--box__letters--area__letter
          = link_to "test", class: "footer__details--box__letters--area__letter--link" do
            会社概要（運営会社）
        %li.footer__details--box__letters--area__letter
          = link_to "test", class: "footer__details--box__letters--area__letter--link" do
            採用情報
        %li.footer__details--box__letters--area__letter
          = link_to "test", class: "footer__details--box__letters--area__letter--link" do
            プレスリリース
        %li.footer__details--box__letters--area__letter
          = link_to "test", class: "footer__details--box__letters--area__letter--link" do
            公式ブログ
        %li.footer__details--box__letters--area__letter
          = link_to "test", class: "footer__details--box__letters--area__letter--link" do
            メルカリロゴ利用ガイドライン
        = link_to "test", class: "footer__details--box__letters--area__logos", target: "_blank" do
          %svg.footer__details--box__letters--area__logos--icon{"aria-hidden": "true", height: "16", viewbox: "0 0 21 16", width: "21"}
            %path{d: "M6.343 15.969c7.61 0 11.773-6.134 11.773-11.444 0-.172 0-.345-.008-.517a8.303 8.303 0 0 0 2.066-2.086 8.576 8.576 0 0 1-2.38.635A4.07 4.07 0 0 0 19.616.329a8.377 8.377 0 0 1-2.63.973 4.186 4.186 0 0 0-3.019-1.27c-2.283 0-4.14 1.803-4.14 4.023 0 .314.041.62.106.918A11.866 11.866 0 0 1 1.404.769a3.936 3.936 0 0 0-.557 2.023c0 1.396.735 2.628 1.84 3.35a4.278 4.278 0 0 1-1.872-.503v.055c0 1.945 1.428 3.577 3.317 3.945-.347.094-.71.141-1.09.141-.266 0-.524-.023-.774-.07.524 1.6 2.057 2.76 3.865 2.792a8.452 8.452 0 0 1-5.14 1.725 8.19 8.19 0 0 1-.985-.054 12.02 12.02 0 0 0 6.335 1.796"}
        = link_to "test", class: "footer__details--box__letters--area__logos", target: "_blank" do
          %svg.footer__details--box__letters--area__logos--icon{"aria-hidden": "true", height: "16", viewbox: "0 0 16 16", width: "16"}
            %path{d: "M15.111 0H.89A.889.889 0 0 0 0 .889V15.11c0 .491.398.889.889.889h7.658V9.813H6.469V7.391h2.078V5.613c0-2.066 1.262-3.193 3.11-3.193.623-.002 1.244.03 1.863.096v2.15h-1.276c-1.002 0-1.197.478-1.197 1.178v1.543h2.397l-.31 2.422h-2.087V16h4.064c.491 0 .889-.398.889-.889V.89A.889.889 0 0 0 15.111 0z"}
  .footer__details--box
    %h2.footer__details--box__title
      ヘルプ&ガイド
    .footer__details--box__letters
      %ul.footer__details--box__letters--area
        %li.footer__details--box__letters--area__letter
          = link_to "test", class: "footer__details--box__letters--area__letter--link" do
            メルカリガイド
        %li.footer__details--box__letters--area__letter
          = link_to "test", class: "footer__details--box__letters--area__letter--link" do
            らくらくメルカリ便
        %li.footer__details--box__letters--area__letter
          = link_to "test", class: "footer__details--box__letters--area__letter--link" do
            ゆうゆうメルカリ便
        %li.footer__details--box__letters--area__letter
          = link_to "test", class: "footer__details--box__letters--area__letter--link" do
            大型メルカリ便
        %li.footer__details--box__letters--area__letter
          = link_to "test", class: "footer__details--box__letters--area__letter--link" do
            車体取引ガイド
        %li.footer__details--box__letters--area__letter
          = link_to "test", class: "footer__details--box__letters--area__letter--link" do
            メルカリあんしん・あんぜん宣言！
        %li.footer__details--box__letters--area__letter
          = link_to "test", class: "footer__details--box__letters--area__letter--link" do
            偽ブランド品撲滅への取り組み
        %li.footer__details--box__letters--area__letter
          = link_to "test", class: "footer__details--box__letters--area__letter--link" do
            メルカリボックス
  .footer__details--box
    %h2.footer__details--box__title
      プライバシーと利用規約
    .footer__details--box__letters
      %ul.footer__details--box__letters--area
        %li.footer__details--box__letters--area__letter
          = link_to "test", class: "footer__details--box__letters--area__letter--link" do
            プライバシーポリシー
        %li.footer__details--box__letters--area__letter
          = link_to "test", class: "footer__details--box__letters--area__letter--link" do
            メルカリ利用規約
        %li.footer__details--box__letters--area__letter
          = link_to "test", class: "footer__details--box__letters--area__letter--link" do
            あんしんスマホサポート制度に関する利用特約
        %li.footer__details--box__letters--area__letter
          = link_to "test", class: "footer__details--box__letters--area__letter--link" do
            コンプライアンスポリシー
    .footer__details--box__letters
      %ul.footer__details--box__letters--area
        %li.footer__details--box__letters--area__letter
          = link_to "test", class: "footer__details--box__letters--area__letter--link" do
            個人データの安全管理に係る基本方針
        %li.footer__details--box__letters--area__letter
          = link_to "test", class: "footer__details--box__letters--area__letter--link" do
            特定商取引に関する表記
        %li.footer__details--box__letters--area__letter
          = link_to "test", class: "footer__details--box__letters--area__letter--link" do
            資金決済法に基づく表示
        %li.footer__details--box__letters--area__letter
          = link_to "test", class: "footer__details--box__letters--area__letter--link" do
            法令遵守と犯罪抑止のために
  .footer__details--box
    %h2.footer__details--box__title
      国
    .footer__details--box__letters
      %ul.footer__details--box__letters--area
        %li.footer__details--box__letters--area__letter
          = link_to "test", class: "footer__details--box__letters--area__letter--link" do
            日本
          = link_to "test", class: "footer__details--box__letters--area__letter--link" do
            United States
.footer__end
  = link_to root_path, class: "footer__end--logo" do
    = image_tag "logo-mercari-white.svg", alt: "Mercari", class: "footer__end--logo"
  %span.footer__end--copyright
    © 2019 Mercari

app/views/top/_header.html.haml
.header
  .header__upper
    .header__upper--leftbox
      = link_to root_path, class: "main_logo" do
        = image_tag "logo-mercari.svg", alt: "mercari", class: "mercari_logo"
    .header__upper--form
      = search_form_for @q ,url: top_search_products_path, method: :get do |f|
        .header__upper--form__input
          = f.search_field :name_or_description_cont_any ,placeholder: "何かお探しですか？"
        %button{type: "search",class: "header__upper--form__search"}
          %svg.header__upper--form__search
            %path{d: "M11.435 10.063h-.723l-.256-.247a5.92 5.92 0 0 0 1.437-3.87 5.946 5.946 0 1 0-5.947 5.947 5.92 5.92 0 0 0 3.87-1.437l.247.256v.723L14.637 16 16 14.637l-4.565-4.574zm-5.489 0A4.111 4.111 0 0 1 1.83 5.946 4.111 4.111 0 0 1 5.946 1.83a4.111 4.111 0 0 1 4.117 4.116 4.111 4.111 0 0 1-4.117 4.117z"}
  .header__lower
    .header__lower--leftbox
      .header__lower--leftbox__search
        = link_to "test", class: "header__lower--leftbox__search--box" do
          %svg.header__lower--leftbox__search--box__icon{"aria-hidden" => "true", :height => "16", :viewbox => "0 0 20 16", :width => "20"}
            %path{d: "M18.799 15.25h-11.5a1.25 1.25 0 1 1 0-2.5h11.5a1.25 1.25 0 0 1 0 2.5zm0-6h-11.5a1.25 1.25 0 1 1 0-2.5h11.5a1.25 1.25 0 0 1 0 2.5zm0-6h-11.5a1.25 1.25 0 1 1 0-2.5h11.5a1.25 1.25 0 0 1 0 2.5zM2 16a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm0-6a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm0-6a2 2 0 1 0 0-4 2 2 0 0 0 0 4z"}
          カテゴリーから探す
      .header__lower--leftbox__search
        = link_to "test", class: "header__lower--leftbox__search--box" do
          %svg.header__lower--leftbox__search--box__icon{"aria-hidden" => "true", :height => "16", :viewbox => "0 0 23 16", :width => "23"}
            %path{d: "M6.315 0L4.473 1.806 2.833.019.73 1.977l1.69 1.84L1.198 5.02c-1.594 1.594-1.594 4.188-.01 5.772L6.3 16h13.272a3.08 3.08 0 0 0 3.077-3.077V3.076A3.08 3.08 0 0 0 19.57 0H6.315zm13.46 12.925a.211.211 0 0 1-.205.205H7.504L3.227 8.771a1.226 1.226 0 0 1-.01-1.71L4.38 5.92l1.28 1.371a2.68 2.68 0 1 0 2.13-1.93L6.433 3.907 7.49 2.87h12.082a.211.211 0 0 1 .206.205v9.848h-.002z"}
          ブランドから探す
    .header__lower--rightbox
      - if user_signed_in?
        .header__lower--rightbox__mypage
          = link_to users_path, class: "header__lower--rightbox__mypage--btn" do
            マイページ
            -# ユーザーマイページのリンクを貼り付け
        .header__lower--rightbox__log_out
          = link_to destroy_user_session_path, method: :delete, class: "header__lower--rightbox__log_out--btn" do
            ログアウト
      - else
        .header__lower--rightbox__sign_up
          = link_to new_user_registration_path, method: :get, class: "header__lower--rightbox__sign_up--btn" do
            新規会員登録
            -#　ユーザー新規会員登録のリンクを貼り付け
        .header__lower--rightbox__log_in
          = link_to user_session_path, class: "header__lower--rightbox__log_in--btn" do
            ログイン

app/views/top/_latest-items.html.haml
.content__main--latest-items__box
  .content__main--latest-items__box--top_bar
    .content__main--latest-items__box--top_bar__title
      レディース新着アイテム
    = link_to products_path, class: "content__main--latest-items__box--top_bar__more-btn" do
      もっと見る
  %ul.content__main--latest-items__box--merchandises
    = render partial: 'merchandises', collection: @ladies, as:'category'
.content__main--latest-items__box
  .content__main--latest-items__box--top_bar
    .content__main--latest-items__box--top_bar__title
      メンズ新着アイテム
    = link_to "test", class: "content__main--latest-items__box--top_bar__more-btn" do
      もっと見る
  %ul.content__main--latest-items__box--merchandises
    = render partial: 'merchandises', collection: @mens, as:'category'
.content__main--latest-items__box
  .content__main--latest-items__box--top_bar
    .content__main--latest-items__box--top_bar__title
      家電・スマホ・カメラ新着アイテム
    = link_to "test", class: "content__main--latest-items__box--top_bar__more-btn" do
      もっと見る
  %ul.content__main--latest-items__box--merchandises
    = render partial: 'merchandises', collection: @electricals, as:'category'
.content__main--latest-items__box
  .content__main--latest-items__box--top_bar
    .content__main--latest-items__box--top_bar__title
      おもちゃ・ホビー・グッズ新着アイテム
    = link_to "test", class: "content__main--latest-items__box--top_bar__more-btn" do
      もっと見る
  %ul.content__main--latest-items__box--merchandises
    = render partial: 'merchandises', collection: @toys, as:'category'

app/views/top/_merchandises.html.haml
%li.content__main--latest-items__box--merchandises__merchandise
  = link_to product_path(category), class: "content__main--latetst-items__box--merchandises__merchandise--block" do
    %figure.content__main--latest-items__box--merchandises__merchandise--block__element
      %figcaption
        %span
          = category.name
      .content__main--latest-items__box--merchandises__merchandise--block__element--pic_box
        = image_tag category.product_images.first.image_url.to_s, class: "lazyloaded", alt: ""
        -if category.purchase_status == "2"
          .item-sold-out-badge-very-small
            %div SOLD
        -else
        %span{"aria-label": "Price"}
          = "¥#{category.price.to_s(:delimited)}"

app/views/top/_put-up-btns.html.haml
= link_to new_product_path, class: "put-up-btns__circle" do
  .put-up-btns__circle--button
    .put-up-btns__circle--button__letter
      出品
    %svg.put-up-btns__circle--button__camera{"aria-hidden": "true", height: "16", viewbox: "0 0 18 16", width: "18"}
      %path{d: "M6.3 0L4.653 1.778H1.8c-.99 0-1.8.8-1.8 1.778v10.666C0 15.2.81 16 1.8 16h14.4c.99 0 1.8-.8 1.8-1.778V3.556c0-.978-.81-1.778-1.8-1.778h-2.853L11.7 0H6.3zM9 13.333c-2.484 0-4.5-1.99-4.5-4.444 0-2.453 2.016-4.445 4.5-4.445s4.5 1.992 4.5 4.445c0 2.453-2.016 4.444-4.5 4.444zm0-1.6c1.59 0 2.88-1.273 2.88-2.844S10.59 6.044 9 6.044c-1.59 0-2.88 1.274-2.88 2.845 0 1.57 1.29 2.844 2.88 2.844z"}

app/views/top/_search-items.html.haml
%ul.content__main--latest-items__box--merchandises
  - @result.each do |result|
    %li.content__main--latest-items__box--merchandises__merchandise
      = link_to product_path(result), class: "content__main--latetst-items__box--merchandises__merchandise--block" do
        %figure.content__main--latest-items__box--merchandises__merchandise--block__element
          %figcaption
            %span
              = result.name
          .content__main--latest-items__box--merchandises__merchandise--block__element--pic_box
            %span{"aria-label": "Price"}
              = "¥#{result.price.to_s(:delimited)}"

app/views/top/search.html.haml
.headers
  = render partial: "top/header"
.content
  %h2
    %span.content__result<>
      = @q.conditions.first.values.first.value
    %span.content__result--text<>
      の検索結果
  .content__num
    1-
    = @result.length
    件表示
    .content__main--latest-items
      = render partial: "top/search-items"
  .content__page
    = paginate @result
.put-up-btns
  = render partial: "top/put-up-btns"
%aside.download-bar
  = render partial: "top/download-bar"
%footer.footer
  = render partial: "top/footer" 