config/routes.rb
Rails.application.routes.draw do

  root 'top#index'
  get "users" => "users#index"
  get 'index' => 'index#index'
  get "/user_identifications/new" => "user_identifications#new"
  post "/user_identifications/new" => "user_identifications#create"
  # View作成用無理やりルーティング。あとで消す。kajitani
  get "users/destroy"

  devise_scope :user do
    post 'users', to: 'devise/registrations#create'
  end
  devise_for :users

  resources :users, only: [:edit, :show, :update]

  resources :signups, only: [:index] do
    collection do
      get 'step1'   
      post 'step1', to: 'signups#step1_validates' 
      get 'step2'  
      post 'step2', to: 'signups#step2' 
      resource :phones,only: [:new] do
        collection do
      post 'step3', to: "signups#step3"
      get  "step4_new", to: "signups#step4_new"
      post "step4", to: "signups#step4"
       end
      end
    end   
  end    

  resources :credit_cards, only: [:new, :show] do
    collection do
      post 'show', to:   'credit_cards#show'
      post 'pay', to:    'credit_cards#pay'
      post 'delete', to: 'credit_cards#delete'
    end
  end

  resources :products do
    member do
      get :purchase
      post :pay, to: "products#pay"
    end

    collection do
      get "cate_children" 
      get "grand_children" 
      get 'top/search'
    end

    resources :likes, only: [:create]
  end
  
  resources :comments, only: [:index, :create] 

end

app/models/address.rb
class Address < ActiveHash::Base
  self.data = [
    {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
    {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
    {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
    {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
    {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
    {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
    {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
    {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
    {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
    {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
    {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
    {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
    {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
    {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
    {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
    {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'},{id: 48, name: '未定'}
]
end

app/models/category.rb
class Category < ApplicationRecord
  has_ancestry
  has_many :products
end

app/models/charge.rb
class Charge < ApplicationRecord
end

app/models/charge_method.rb
class ChargeMethod < ApplicationRecord
  has_many :products
  has_ancestry
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  belongs_to :user

  validates :content, presence: true
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
  has_many :products
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/moredit_card.rb
class MoreditCard < ApplicationRecord
end

app/models/period.rb
class Period < ApplicationRecord
  has_ancestry
  has_many :products
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :user
  validates :number, presence: true
  validates :comfirm_number, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  
  belongs_to :user
  belongs_to :category, optional: true
  belongs_to :period,   optional: true
  belongs_to :charge_method, optional: true

  has_many  :product_images
  accepts_nested_attributes_for :product_images

  belongs_to_active_hash :address
  belongs_to_active_hash :status
  belongs_to_active_hash :period
  belongs_to_active_hash :size

  def previous
    Product.where("id < ?", self.id).order("id DESC").first
  end
 
  def next
    Product.where("id > ?", self.id).order("id ASC").first
  end
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product
  mount_uploader :image_url, ProductImagesUploader
end

app/models/send_area.rb
class SendArea < ApplicationRecord
  belongs_to :products ,optional: true
end

app/models/send_method.rb
class SendMethod < ActiveHash::Base
end

app/models/sendmethod.rb
class Sendmethod < ActiveHash::Base
  self.data = [
    {id: 1, name: '未定'}, {id: 2, name: 'らくらくメルカリ便'}, {id: 3, name: 'ゆうメール'},
    {id: 4, name: 'レターパック'}, {id: 5, name: '普通郵便(定形、定形外)'}, {id: 6, name: 'クロネコヤマト'},
    {id: 7, name: 'ゆうパック'}, {id: 8, name: 'クリックポスト'}, {id: 9, name: 'ゆうパケット'}
]
end

app/models/size.rb
class Size < ActiveHash::Base
  self.data = [
    {id: 1, size: 'XXS以下'}, {id: 2, size: 'XS(SS)'}, {id: 3, size: 'S'},
    {id: 4, size: 'M'}, {id: 5, size: 'L'}, {id: 6, size: 'XL(LL)'},
    {id: 7, size: '2XL(3L)'}, {id: 8, size: '3XL(4L)'}, {id: 9, size: '4XL(5L)以上'},
    {id: 10, size: 'FREE SIZE'}
]
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
    {id: 1, status: '新品、未使用'}, {id: 2, status: '未使用に近い'}, {id: 3, status: '目立った傷や汚れなし'},
    {id: 4, status: 'やや傷や汚れあり'}, {id: 5, status: '傷や汚れあり'}, {id: 6, status: '全体的に状態が悪い'}
]
end

app/models/user.rb
class User < ApplicationRecord
  has_one :phone
  accepts_nested_attributes_for :phone

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         number = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{7,100}+\z/i
         validates :password, presence: true,length: { minimum: 7 }  , format: { with: number }
         validates :lastname, presence: true
         validates :firstname, presence: true
         validates :firstname_kana, presence: true
         validates :lastname_kana, presence: true
         validates :birthday, presence: true
         validates :email, presence: true
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  
  require "payjp"

  def new
    @exp_month = ["--", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"]

    credit_card = CreditCard.where(user_id: current_user.id)
    redirect_to action: "show" if credit_card.exists?
  end

  #payjpとCreditCardデータベース作成
  def pay
    Payjp.api_key = Rails.application.credentials.PAYJP_PRIVATE_KEY
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
        card: params['payjp-token'],
        metadata: {user_id: current_user.id}
      )
      @credit_card = CreditCard.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @credit_card.save
        redirect_to action: "show"
      else
        recirect_to action: "pay"
      end
    end
  end
  
  def delete
    credit_card = CreditCard.find_by(user_id: current_user.id)
    if credit_card.blank?
    else
      Payjp.api_key = Rails.application.credentials.PAYJP_PRIVATE_KEY
      customer = Payjp::Customer.retrieve(credit_card.customer_id)
      customer.delete
      credit_card.delete
    end
      redirect_to controller: "top", action: "index"
  end

  def show
    credit_card = CreditCard.find_by(user_id: current_user.id)
    if credit_card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = Rails.application.credentials.PAYJP_PRIVATE_KEY
      customer = Payjp::Customer.retrieve(credit_card.customer_id)
      @default_card_info = customer.cards.retrieve(credit_card.card_id)
    end
  end
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/credit_cards/new.html.haml
%body
  .rccWrapper
    = render './shareParts/topHeader'
    .main
      =render './shareParts/topSidebar'
      = form_with(model: @credit_card, local: true, url: pay_credit_cards_path, class: "registrationForm") do |f|
        %h2.registrationForm__top クレジットカード情報入力
        .registrationForm__form
          .registrationForm__form__cardNo
            .registrationForm__form__cardNo__caption.top
              %h3.formCaption カード番号
              %span.red 必須
            = f.text_field :number, id: "number", class: "number input", placeholder: "半角数字のみ"
            .registrationForm__form__cardNo__icon
              %ul.registrationForm__form__cardNo__icon__lists
                %li
                  = image_tag("https://www-mercari-jp.akamaized.net/assets/img/card/visa.svg?2356214421", class: "cardIcon")
                %li
                  = image_tag("https://www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?2356214421", class: "cardIcon")
                %li
                  = image_tag("https://www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?2356214421", class: "cardIcon")
                %li
                  = image_tag("https://www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?2356214421", class: "cardIcon")
                %li
                  = image_tag("https://www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?2356214421", class: "cardIcon")
                %li
                  = image_tag("https://www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?2356214421", class: "cardIcon")
                %li
                  = image_tag("https://www-mercari-jp.akamaized.net/assets/img/card/discover.svg?2356214421", class: "cardIcon")
          .registrationForm__form__expirationDate
            .registrationForm__expirationDate__caption.top
              %h3.formCaption 有効期限
              %span.red 必須
            .registrationForm__form__expirationDate__input
              = f.select :exp_month, @exp_month, {}, {id: "exp_month", class: "exp_month"}
              %span 月
              %select{id: "exp_year", name: "exp_year", type: "text"}
                %option{value: ""}--
                %option{value: "2019"}19
                %option{value: "2020"}20
                %option{value: "2021"}21
                %option{value: "2022"}22
                %option{value: "2023"}23
                %option{value: "2024"}24
                %option{value: "2025"}25
                %option{value: "2026"}26
                %option{value: "2027"}27
                %option{value: "2028"}28
                %option{value: "2029"}29
                %option{value: "2030"}30
              %span 年
          .registrationForm__form__securityCode
            .registrationForm__form__securityCode__caption.top
              %h3.formCaption セキュリコード
              %span.red 必須
            .registrationForm__form__securityCode__input
              = f.text_field :cvc, id: :cvc, class: "input cvc", placeholder: "カード背面4桁もしくは3桁の番号"
            .registrationForm__form__securityCode__help
              %span ?
              カード裏面の番号とは?
          #card_token
          = f.submit id: "token_submit", class: "registrationForm__form__submit red", value:"追加する"

    = render './shareParts/topFooter'

app/views/credit_cards/show.html.haml
%label 登録クレジットカード情報
%br
= "**** **** **** " + @default_card_info.last4
%br
- exp_month = @default_card_info.exp_month.to_s
- exp_year = @default_card_info.exp_year.to_s.slice(2,3)
= exp_month + " / " + exp_year
= form_tag(delete_credit_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do
  %input{ type: "hidden", name: "credit_card_id", value: "" }
  %button 削除する