config/routes.rb
Rails.application.routes.draw do

  root 'top#index'
  get "users" => "users#index"
  get 'index' => 'index#index'
  get "/user_identifications/new" => "user_identifications#new"
  post "/user_identifications/new" => "user_identifications#create"
  # View作成用無理やりルーティング。あとで消す。kajitani
  get "users/destroy"

  devise_scope :user do
    post 'users', to: 'devise/registrations#create'
  end
  devise_for :users

  resources :users, only: [:edit, :show, :update]

  resources :signups, only: [:index] do
    collection do
      get 'step1'   
      post 'step1', to: 'signups#step1_validates' 
      get 'step2'  
      post 'step2', to: 'signups#step2' 
      resource :phones,only: [:new] do
        collection do
      post 'step3', to: "signups#step3"
      get  "step4_new", to: "signups#step4_new"
      post "step4", to: "signups#step4"
       end
      end
    end   
  end    

  resources :credit_cards, only: [:new, :show] do
    collection do
      post 'show', to:   'credit_cards#show'
      post 'pay', to:    'credit_cards#pay'
      post 'delete', to: 'credit_cards#delete'
    end
  end

  resources :products do
    member do
      get :purchase
      post :pay, to: "products#pay"
    end

    collection do
      get "cate_children" 
      get "grand_children" 
      get 'top/search'
    end

    resources :likes, only: [:create]
  end
  
  resources :comments, only: [:index, :create] 

end

app/models/address.rb
class Address < ActiveHash::Base
  self.data = [
    {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
    {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
    {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
    {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
    {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
    {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
    {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
    {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
    {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
    {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
    {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
    {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
    {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
    {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
    {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
    {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'},{id: 48, name: '未定'}
]
end

app/models/category.rb
class Category < ApplicationRecord
  has_ancestry
  has_many :products
end

app/models/charge.rb
class Charge < ApplicationRecord
end

app/models/charge_method.rb
class ChargeMethod < ApplicationRecord
  has_many :products
  has_ancestry
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  belongs_to :user

  validates :content, presence: true
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
  has_many :products
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/moredit_card.rb
class MoreditCard < ApplicationRecord
end

app/models/period.rb
class Period < ApplicationRecord
  has_ancestry
  has_many :products
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :user
  validates :number, presence: true
  validates :comfirm_number, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  
  belongs_to :user
  belongs_to :category, optional: true
  belongs_to :period,   optional: true
  belongs_to :charge_method, optional: true

  has_many  :product_images
  accepts_nested_attributes_for :product_images

  belongs_to_active_hash :address
  belongs_to_active_hash :status
  belongs_to_active_hash :period
  belongs_to_active_hash :size

  def previous
    Product.where("id < ?", self.id).order("id DESC").first
  end
 
  def next
    Product.where("id > ?", self.id).order("id ASC").first
  end
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product
  mount_uploader :image_url, ProductImagesUploader
end

app/models/send_area.rb
class SendArea < ApplicationRecord
  belongs_to :products ,optional: true
end

app/models/send_method.rb
class SendMethod < ActiveHash::Base
end

app/models/sendmethod.rb
class Sendmethod < ActiveHash::Base
  self.data = [
    {id: 1, name: '未定'}, {id: 2, name: 'らくらくメルカリ便'}, {id: 3, name: 'ゆうメール'},
    {id: 4, name: 'レターパック'}, {id: 5, name: '普通郵便(定形、定形外)'}, {id: 6, name: 'クロネコヤマト'},
    {id: 7, name: 'ゆうパック'}, {id: 8, name: 'クリックポスト'}, {id: 9, name: 'ゆうパケット'}
]
end

app/models/size.rb
class Size < ActiveHash::Base
  self.data = [
    {id: 1, size: 'XXS以下'}, {id: 2, size: 'XS(SS)'}, {id: 3, size: 'S'},
    {id: 4, size: 'M'}, {id: 5, size: 'L'}, {id: 6, size: 'XL(LL)'},
    {id: 7, size: '2XL(3L)'}, {id: 8, size: '3XL(4L)'}, {id: 9, size: '4XL(5L)以上'},
    {id: 10, size: 'FREE SIZE'}
]
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
    {id: 1, status: '新品、未使用'}, {id: 2, status: '未使用に近い'}, {id: 3, status: '目立った傷や汚れなし'},
    {id: 4, status: 'やや傷や汚れあり'}, {id: 5, status: '傷や汚れあり'}, {id: 6, status: '全体的に状態が悪い'}
]
end

app/models/user.rb
class User < ApplicationRecord
  has_one :phone
  accepts_nested_attributes_for :phone

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         number = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{7,100}+\z/i
         validates :password, presence: true,length: { minimum: 7 }  , format: { with: number }
         validates :lastname, presence: true
         validates :firstname, presence: true
         validates :firstname_kana, presence: true
         validates :lastname_kana, presence: true
         validates :birthday, presence: true
         validates :email, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :move_to_signin
  before_action :search
  def move_to_signin
    redirect_to user_session_path unless user_signed_in?
  end
  def index
  end
  def show
    @user = User.find(params[:id])
    @user = current_user
    @user_identification = UserIdentification.find_by(user_id: @user.id)
  end
  def edit
    @user = User.find(params[:id])
  end
  def destroy
  end
  def update
    user = User.find(params[:id])
    if user.id == current_user.id
      user.update_columns(user_params.to_hash)
      redirect_to edit_user_path(current_user.id)
    end
  end
  private
  def user_params
    params.require(:user).permit(:nickname,:profiles)
  end

  def search
    @q = Product.ransack(params[:q])
    @result = @q.result(distinct: true)
  end
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/users/destroy.html.haml
.headers
  = render partial: "top/header"

%main.mypage-container
  .mypage-content
    / ログアウト
    %section.mypage-content__logout
      %form.mypage-content__logout-form
        .mypage-content__logout-form__content
          = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn-default btn-red"

  .mypage-side
    %nav.mypage-side-nav
      %ul.mypage-side-nav__list
        %li
          = link_to users_path, class: "mypage-side-nav__list__item active" do
            マイページ
            = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
        %li
          = link_to users_path, class: "mypage-side-nav__list__item" do
            お知らせ
            = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
        %li
          = link_to users_path, class: "mypage-side-nav__list__item" do
            やることリスト
            = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
        %li
          = link_to users_path, class: "mypage-side-nav__list__item" do
            いいね！一覧
            = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
        %li
          = link_to users_path, class: "mypage-side-nav__list__item" do
            出品する
            = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
        %li
          = link_to users_path, class: "mypage-side-nav__list__item" do
            出品した商品 - 出品中
            = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
        %li
          = link_to users_path, class: "mypage-side-nav__list__item" do
            出品した商品 - 取引中
            = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
        %li
          = link_to users_path, class: "mypage-side-nav__list__item" do
            出品した商品 - 売却済み
            = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
        %li
          = link_to users_path, class: "mypage-side-nav__list__item" do
            購入した商品 - 取引中
            = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
        %li
          = link_to users_path, class: "mypage-side-nav__list__item" do
            購入した商品 - 過去の取引
            = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
        %li
          = link_to users_path, class: "mypage-side-nav__list__item" do
            ニュース一覧
            = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
        %li
          = link_to users_path, class: "mypage-side-nav__list__item" do
            評価一覧
            = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
        %li
          = link_to users_path, class: "mypage-side-nav__list__item" do
            ガイド
            = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
        %li
          = link_to users_path, class: "mypage-side-nav__list__item" do
            お問い合わせ
            = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
      %h3.mypage-side-nav__head メルペイ
      %ul.mypage-side-nav__list.margin
        %li
          = link_to users_path, class: "mypage-side-nav__list__item" do
            売上・振込申請
            = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
        %li
          = link_to users_path, class: "mypage-side-nav__list__item" do
            ポイント
            = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
      %h3.mypage-side-nav__head 設定
      %ul.mypage-side-nav__list.margin
        %li
          = link_to users_path, class: "mypage-side-nav__list__item" do
            プロフィール
            = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
        %li
          = link_to users_path, class: "mypage-side-nav__list__item" do
            発送元・お届け先住所変更
            = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
        %li
          = link_to users_path, controller: "payments", method: :get, action: "index", class: "mypage-side-nav__list__item" do
            支払い方法
            = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
        %li
          = link_to users_path, class: "mypage-side-nav__list__item" do
            メール/パスワード
            = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
        %li
          = link_to users_path, class: "mypage-side-nav__list__item" do
            本人情報
            = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
        %li
          = link_to users_path, class: "mypage-side-nav__list__item" do
            電話番号の確認
            = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
        %li
          = link_to users_path, method: :delete, action: "destroy", class: "mypage-side-nav__list__item" do
            ログアウト
            = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"

%aside.download-bar
  = render partial: "top/download-bar"
.footer
  = render partial: "top/footer"

app/views/users/edit.html.haml
.user_edit
  = render './shareParts/topHeader'
.mainedit
  .main__side
    =render './shareParts/topSidebar'
  .main__top
    = form_with(model: @user,url: user_path(current_user.id),method: :patch,  local: true) do |form|
      .main__top--pro プロフィール 
      .field
        = form.text_field :nickname, class:"main__top--nickname", placeholder:"ニックネーム"
      .field
        = form.text_field :profiles, class:"main__top--text", placeholder:"初めまして　よろしくお願いしまうま"
      .actions
        = form.submit "変更する", class:"main__top--change"
%footer.footer
  = render './shareParts/topFooter'

app/views/users/index.html.haml
.headers
  .header
    .header__upper
      .header__upper--leftbox
        = link_to root_path, class: "main_logo" do
          = image_tag "https://web-jp-assets.mercdn.net/_next/static/images/logo-acdd90ac4f472d5a6f7a330d33ab1225.svg", alt: "mercari", class: "mercari_logo"
      %form.header__upper--form{action: "test"}
        %input.header__upper--form__input{name: "keyword", placeholder: "何かお探しですか？", type: "search", value: ""}/
        %button.header__upper--form__search
          %svg.header__upper--form__search--search-btn{"aria-hidden" => "true", :height => "16", :viewbox => "0 0 16 16", :width => "16"}
            %path{d: "M11.435 10.063h-.723l-.256-.247a5.92 5.92 0 0 0 1.437-3.87 5.946 5.946 0 1 0-5.947 5.947 5.92 5.92 0 0 0 3.87-1.437l.247.256v.723L14.637 16 16 14.637l-4.565-4.574zm-5.489 0A4.111 4.111 0 0 1 1.83 5.946 4.111 4.111 0 0 1 5.946 1.83a4.111 4.111 0 0 1 4.117 4.116 4.111 4.111 0 0 1-4.117 4.117z", fill: "currentColor", "fill-rule": "nonzero"}
    .header__lower
      .header__lower--leftbox
        .header__lower--leftbox__search
          = link_to "test", class: "header__lower--leftbox__search--box" do
            %svg.header__lower--leftbox__search--box__icon{"aria-hidden" => "true", :height => "16", :viewbox => "0 0 20 16", :width => "20"}
              %path{d: "M18.799 15.25h-11.5a1.25 1.25 0 1 1 0-2.5h11.5a1.25 1.25 0 0 1 0 2.5zm0-6h-11.5a1.25 1.25 0 1 1 0-2.5h11.5a1.25 1.25 0 0 1 0 2.5zm0-6h-11.5a1.25 1.25 0 1 1 0-2.5h11.5a1.25 1.25 0 0 1 0 2.5zM2 16a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm0-6a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm0-6a2 2 0 1 0 0-4 2 2 0 0 0 0 4z", fill: "currentColor", "fill-rule": "nonzero"}
            カテゴリーから探す
        .header__lower--leftbox__search
          = link_to "test", class: "header__lower--leftbox__search--box" do
            %svg.header__lower--leftbox__search--box__icon{"aria-hidden" => "true", :height => "16", :viewbox => "0 0 23 16", :width => "23"}
              %path{d: "M6.315 0L4.473 1.806 2.833.019.73 1.977l1.69 1.84L1.198 5.02c-1.594 1.594-1.594 4.188-.01 5.772L6.3 16h13.272a3.08 3.08 0 0 0 3.077-3.077V3.076A3.08 3.08 0 0 0 19.57 0H6.315zm13.46 12.925a.211.211 0 0 1-.205.205H7.504L3.227 8.771a1.226 1.226 0 0 1-.01-1.71L4.38 5.92l1.28 1.371a2.68 2.68 0 1 0 2.13-1.93L6.433 3.907 7.49 2.87h12.082a.211.211 0 0 1 .206.205v9.848h-.002z", fill: "currentColor", "fill-rule": "nonzero"}
            ブランドから探す
      .header__lower--rightbox
        .header__lower--rightbox__sign_up
          = link_to destroy_user_session_path, method: :delete, class: "header__lower--rightbox__sign_up--btn" do
            新規会員登録
        .header__lower--rightbox__log_in
          = link_to new_credit_card_path, class: "header__lower--rightbox__log_in--btn" do
            ログイン
%main.mypage-container
  .mypage-content
    %section.mypage-user-icon
      = link_to users_path do
        %figure
          = image_tag "https://static.mercdn.net/thumb/members/103058894.jpg?1538909507", size: "60x60"
        %h2.mypage-user-icon__name.bold
          = current_user.nickname
        .mypage-user-icon__number
          .mypage-user-icon__number--rate
            評価
            %span.bold
              0
          .mypage-user-icon__number--display
            出品数
            %span.bold
              15
    %section.mypage-content__tab-container-notification
      %ul.mypage-content__tabs
        %li.mypage-content__tabs--active
          %h3.mypage-content__tabs__head
            = link_to users_path do
              お知らせ
        %li.mypage-content__tabs--non-active
          %h3
            = link_to users_path, class: "mypage-content__tabs__head" do
              やることリスト
      .mypage-content__tab-content
        %ul.mypage-content__tab-content__item-list
          %li
            = link_to users_path, class: "mypage-content__tab-content__item-list__link" do
              %figure
                = image_tag("https://static.mercdn.net/images/mercari_profile.png", size: "48x48")
              .mypage-content__tab-content__item-list__body
                .mypage-content__tab-content__item-list__body--text
                  時間が足りないよやること多すぎだよ眠いよ寝よう
                %time
                  = icon "far", "clock"
                  %span 1日前
              = icon "fas", "angle-right", class: "mypage-content__tab-content__item-list__icon"
          %li
            = link_to users_path, class: "mypage-content__tab-content__item-list__link" do
              %figure
                = image_tag("https://static.mercdn.net/thumb/photos/m52914734455_1.jpg?1557221827", size: "48x48")
              .mypage-content__tab-content__item-list__body
                .mypage-content__tab-content__item-list__body--text
                  いいね！したシャツにコメントがつきました。
                %time
                  = icon "far", "clock"
                  %span 5時間前
              = icon "fas", "angle-right", class: "mypage-content__tab-content__item-list__icon"
          %li
            = link_to users_path, class: "mypage-content__tab-content__item-list__link" do
              %figure
                = image_tag("https://static.mercdn.net/images/mercari_profile.png", size: "48x48")
              .mypage-content__tab-content__item-list__body
                .mypage-content__tab-content__item-list__body--text
                  「メルペイスマート払い」なら今だけ最大3％還元！詳しくはこちら
                %time
                  = icon "far", "clock"
                  %span 5週間前
              = icon "fas", "angle-right", class: "mypage-content__tab-content__item-list__icon"
          %li
            = link_to users_path, class: "mypage-content__tab-content__item-list__link" do
              %figure
                = image_tag("https://static.mercdn.net/images/mercari_profile.png", size: "48x48")
              .mypage-content__tab-content__item-list__body
                .mypage-content__tab-content__item-list__body--text
                  最大P3000もらえる！買うしかないキャンペーン開催中！！
                %time
                  = icon "far", "clock"
                  %span 4時間前
              = icon "fas", "angle-right", class: "mypage-content__tab-content__item-list__icon"
          %li
            = link_to users_path, class: "mypage-content__tab-content__item-list__link" do
              %figure
                = image_tag("https://static.mercdn.net/thumb/photos/m97045633952_1.jpg?1568523458", size: "48x48")
              .mypage-content__tab-content__item-list__body
                .mypage-content__tab-content__item-list__body--text
                  「サッカー用コーン」を購入しました。取引が完了しました。
                %time
                  = icon "far", "clock"
                  %span 1分前
              = icon "fas", "angle-right", class: "mypage-content__tab-content__item-list__icon"
          %li.mypage-content__tab-content__item-list__index
            = link_to users_path do
              一覧を見る
    %section.mypage-content__tab-container
      %h2.mypage-content__head.bold 購入した商品
      %ul.mypage-content__tabs
        %li.mypage-content__tabs--active
          %h3.mypage-content__tabs__head
            = link_to users_path do
              取引中
        %li.mypage-content__tabs--non-active
          %h3.mypage-content__tabs__head
            = link_to users_path do
              過去の取引
      .mypage-content__tab-content
        %ul.mypage-content__tab-content-active
          %li.mypage-content__tab-content__not-found.bold
            取引中の商品がありません
  .mypage-side
    =render './shareParts/topSidebar'
    -# %nav.mypage-side-nav
    -#   %ul.mypage-side-nav__list
    -#     %li
    -#       = link_to users_path, class: "mypage-side-nav__list__item active" do
    -#         マイページ
    -#         = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
    -#     %li
    -#       = link_to users_path, class: "mypage-side-nav__list__item" do
    -#         お知らせ
    -#         = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
    -#     %li
    -#       = link_to users_path, class: "mypage-side-nav__list__item" do
    -#         やることリスト
    -#         = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
    -#     %li
    -#       = link_to users_path, class: "mypage-side-nav__list__item" do
    -#         いいね！一覧
    -#         = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
    -#     %li
    -#       = link_to users_path, class: "mypage-side-nav__list__item" do
    -#         出品する
    -#         = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
    -#     %li
    -#       = link_to users_path, class: "mypage-side-nav__list__item" do
    -#         出品した商品 - 出品中
    -#         = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
    -#     %li
    -#       = link_to users_path, class: "mypage-side-nav__list__item" do
    -#         出品した商品 - 取引中
    -#         = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
    -#     %li
    -#       = link_to users_path, class: "mypage-side-nav__list__item" do
    -#         出品した商品 - 売却済み
    -#         = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
    -#     %li
    -#       = link_to users_path, class: "mypage-side-nav__list__item" do
    -#         購入した商品 - 取引中
    -#         = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
    -#     %li
    -#       = link_to users_path, class: "mypage-side-nav__list__item" do
    -#         購入した商品 - 過去の取引
    -#         = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
    -#     %li
    -#       = link_to users_path, class: "mypage-side-nav__list__item" do
    -#         ニュース一覧
    -#         = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
    -#     %li
    -#       = link_to users_path, class: "mypage-side-nav__list__item" do
    -#         評価一覧
    -#         = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
    -#     %li
    -#       = link_to users_path, class: "mypage-side-nav__list__item" do
    -#         ガイド
    -#         = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
    -#     %li
    -#       = link_to users_path, class: "mypage-side-nav__list__item" do
    -#         お問い合わせ
    -#         = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
    -#   %h3.mypage-side-nav__head メルペイ
    -#   %ul.mypage-side-nav__list.margin
    -#     %li
    -#       = link_to users_path, class: "mypage-side-nav__list__item" do
    -#         売上・振込申請
    -#         = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
    -#     %li
    -#       = link_to users_path, class: "mypage-side-nav__list__item" do
    -#         ポイント
    -#         = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
    -#   %h3.mypage-side-nav__head 設定
    -#   %ul.mypage-side-nav__list.margin
    -#     %li
    -#       = link_to edit_user_path(current_user.id), class: "mypage-side-nav__list__item" do
    -#         プロフィール
    -#         = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
    -#     %li
    -#       = link_to users_path, class: "mypage-side-nav__list__item" do
    -#         発送元・お届け先住所変更
    -#         = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
    -#     %li
    -#       = link_to users_path, controller: "payments", method: :get, action: "index", class: "mypage-side-nav__list__item" do
    -#         支払い方法
    -#         = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
    -#     %li
    -#       = link_to users_path, class: "mypage-side-nav__list__item" do
    -#         メール/パスワード
    -#         = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
    -#     %li
    -#       = link_to users_path, class: "mypage-side-nav__list__item" do
    -#         本人情報
    -#         = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
    -#     %li
    -#       = link_to users_path(current_user.id), class: "mypage-side-nav__list__item" do
    -#         電話番号の確認
    -#         = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"
    -#     %li
    -#       = link_to "", method: :delete, action: "destroy", class: "mypage-side-nav__list__item" do
    -#         ログアウト
    -#         = icon "fas", "angle-right" , class: "mypage-side-nav__list__icon"

app/views/users/logout.html.haml
%main.mypage-container
  .mypage-content
    / ログアウト
    %section.mypage-content__logout
      %form.mypage-content__logout-form
        .mypage-content__logout-form__content
          = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn-default btn-red"