config/routes.rb
Rails.application.routes.draw do

  root 'top#index'
  get "users" => "users#index"
  get 'index' => 'index#index'
  get "/user_identifications/new" => "user_identifications#new"
  post "/user_identifications/new" => "user_identifications#create"
  # View作成用無理やりルーティング。あとで消す。kajitani
  get "users/destroy"

  devise_scope :user do
    post 'users', to: 'devise/registrations#create'
  end
  devise_for :users

  resources :users, only: [:edit, :show, :update]

  resources :signups, only: [:index] do
    collection do
      get 'step1'   
      post 'step1', to: 'signups#step1_validates' 
      get 'step2'  
      post 'step2', to: 'signups#step2' 
      resource :phones,only: [:new] do
        collection do
      post 'step3', to: "signups#step3"
      get  "step4_new", to: "signups#step4_new"
      post "step4", to: "signups#step4"
       end
      end
    end   
  end    

  resources :credit_cards, only: [:new, :show] do
    collection do
      post 'show', to:   'credit_cards#show'
      post 'pay', to:    'credit_cards#pay'
      post 'delete', to: 'credit_cards#delete'
    end
  end

  resources :products do
    member do
      get :purchase
      post :pay, to: "products#pay"
    end

    collection do
      get "cate_children" 
      get "grand_children" 
      get 'top/search'
    end

    resources :likes, only: [:create]
  end
  
  resources :comments, only: [:index, :create] 

end

app/models/product.rb
class Product < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  
  belongs_to :user
  belongs_to :category, optional: true
  belongs_to :period,   optional: true
  belongs_to :charge_method, optional: true

  has_many  :product_images
  accepts_nested_attributes_for :product_images

  belongs_to_active_hash :address
  belongs_to_active_hash :status
  belongs_to_active_hash :period
  belongs_to_active_hash :size

  def previous
    Product.where("id < ?", self.id).order("id DESC").first
  end
 
  def next
    Product.where("id > ?", self.id).order("id ASC").first
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :search

  def purchase
    @product = Product.find(params[:id])
    credit_card = CreditCard.where(user_id: current_user.id).first
    @product_image = ProductImage.where(product_id: @product.id)
    #登録された情報がない場合にカード登録画面に移動
    if credit_card.blank?
      redirect_to new_credit_card_path
    else
      #保管した顧客IDでpayjpから情報取得
      Payjp.api_key = "sk_test_0d9443b9a1a637b9456b6f24"
      #保管したカードIDでpayjpから情報取得、カード情報表示のためインスタンス変数に代入
      customer = Payjp::Customer.retrieve(credit_card.customer_id)
      @default_card_information = customer.cards.retrieve(credit_card.card_id)
    end
  end
  def pay
    @product = Product.find(params[:id])
    credit_card = CreditCard.where(user_id: current_user.id).first
    Payjp.api_key = 'sk_test_0d9443b9a1a637b9456b6f24'
     payjp = Payjp::Charge.create(
    :amount => @product.price,            #支払金額
    # :card  => params['payjp-token'],
    :customer => credit_card.customer_id, #顧客ID
    :currency => 'jpy',                   #単位：日本円
    :description => '決済に関する説明'
    )
    @product.purchase_status = "2"
    @product.save
    redirect_to product_path
  end
  
  def index
  end

  def show
    @user = User.find(@product.user_id)
    @product_image = ProductImage.find_by(product_id: @product.id)
    @category = Category.find_by(id: @product.category_id)
    @product_user_other = Product.where.not(id: @product.id).where(user_id: @product.user_id)
    @product_user_other_image = ProductImage.where(product_id: @product_user_other)
    @charge_method = ChargeMethod.find_by(id: @product.bearsize_id)
    @charge_method2 = ChargeMethod.find_by(id: @product.sendmethod_id)
    @category_same = Product.where.not(id: @product.id).where(category_id: @product.category_id)
    @other_product_image = ProductImage.where(product_id: @category_same)
  end

  def destroy
    @product.destroy if @product.user_id == current_user.id
    redirect_to root_path
  end

  def new
    @product = Product.new
    @product.product_images.build
  end

  def create
    @product = Product.new(product_params)
    @product.purchase_status = "1"

    respond_to do |format|
      if @product.save
        params[:product_images][:image].each do |image|
          @product.product_images.create(image_url: image, product_id: @product.id)
        end
        format.html{redirect_to root_path, notice: '商品を登録しました'}
      else
        @product.product_images.build
        format.html{render action: 'new'}
      end
    end
  end

  def edit
    gon.product = @product
    gon.product_images = @product.product_images

    #写真のデータをバイナリデータに
    require 'base64'
    require 'aws-sdk'
    gon.product_images_binary_datas =[]

    #本番環境と開発環境での場合分け
    if Rails.env.production?
      client = Aws::S3::Client.new(
        region: 'ap-northeast-1',
        access_key_id: Rails.application.credentials.aws[:access_key_id],
        secret_access_key: Rails.application.credentials.aws[:secret_access_key],
        )
      @product.product_images.each do |img|
        binary_data = client.get_object(bucket: 'freemarketsampleyakan58a', key: img.image_url.file.path).body.read
        gon.product_images_binary_datas << Base64.strict_encode64(binary_data)
      end

    else
      @product.product_images.each do |img|
        binary_data = File.read(img.image_url.file.file)
        gon.product_images_binary_datas << Base64.strict_encode64(binary_data)
      end
    end
  end


  def update

    # 登録済画像のidの配列を生成
    ids = @product.product_images.map{|img| img.id }
    # 登録済画像のうち、編集後もまだ残っている画像のidの配列を生成(文字列から数値に変換)
    exist_ids = registered_image_params[:ids].map(&:to_i)
    # 登録済画像が残っていない場合(配列に０が格納されている)、配列を空にする
    exist_ids.clear if exist_ids[0] == 0

    if (exist_ids.length != 0 || new_image_params[:images][0] != " ") && @product.update(product_edit_params)
      # 登録済画像のうち削除ボタンをおした画像を削除
      unless ids.length == exist_ids.length
        # 削除する画像のidの配列を生成
        delete_ids = ids - exist_ids
        delete_ids.each do |id|
          @product.product_images.find(id).destroy
        end
      end

      unless new_image_params[:images][0] == " "
        new_image_params[:images].each do |img|
          @product.product_images.create(image_url: img, product_id: @product.id)
        end
      end
      redirect_to root_path
      
      flash[:notice] = '編集が完了しました'
    else
      flash[:alert] = '未入力項目があります'
      redirect_back(fallback_location: root_path)
    end
  end

  private
  def search
    @q = Product.ransack(params[:q])

    @result = @q.result(distinct: true)
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :brand, :price, :status_id, :category_id, :size_id, :status_id, :bearsize_id, :sendmethod_id, :address_id, :period_id, :charge_method_id, product_images_attributes: [:image_url]).merge(user_id: current_user.id)
  end
  def product_edit_params
    params.require(:product).permit(:name, :description, :brand, :price, :status_id, :category_id, :size_id, :status_id, :bearsize_id, :sendmethod_id, :address_id, :period_id, :charge_method_id).merge(user_id: current_user.id)
  end

  def registered_image_params
    params.require(:registered_images_ids).permit({ids: []})
  end

  def new_image_params
    params.require(:new_images).permit({images: []})
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_footer.haml
%footer.footer__container1
  .box.box__1
    = link_to "プライバシーポリシー",class:"link"
  .box.box__2
    = link_to "メルカリ利用規約",class:"link"
  .box.box__3
    = link_to "特定商取引に関する表記",class:"link"
  .footer__container2
    .box.box__4
      = link_to root_path do
        = image_tag "https://www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?3649802486", alt:"mercari", height:"65", width: "80"
    %small © Mercari, Inc.

app/views/products/_image.html.haml
.sell__upload--box
  .form__group--name
    %label
      出品画像
      %span.form__require 必須
    %p 最大10枚までアップロードできます
    %form.sell__form
      .sell__upload--drop--box
        = form_for @product do |f|
          = f.hidden_field :image
          = f.label "ドラッグアンドドロップ",class: "l1"
          %br/
          = f.label "またはクリックしてファイルをアップロード",class: "l2"
          = f.file_field :image ,multiple: true, class: "image"

app/views/products/purchase.html.haml
-# %body
-#   .ppWrapper
-#     %header.header
-#       %h1.header__logo
-#         =link_to image_tag("https://www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?1855818912", class: "header__logo__icon"), "#topへ移動", class: "opa"
-#     .main
-#       %h2.top 購入内容の確認
-#       .product
-#         .product__info
-#           =image_tag("https://rr.img.naver.jp/mig?src=http%3A%2F%2Fimgcc.naver.jp%2Fkaze%2Fmission%2FUSER%2F20130322%2F18%2F1563448%2F32%2F403x403xa3d346eed3cc8edcd8eb176e.jpg&twidth=1000&theight=0&qlt=80&res_format=jpg&op=r", class: "product__info__image")
-#           .product__info__name いい女
-#         %form
-#           .product__price
-#             .product__price--left $1,000,000
-#             .product__price--right 送料込み
-#           .point.btn ポイントはありません
-#           .product__payment
-#             .product__payment--left 支払い金額
-#             .product__payment--right $1,000,000
-#           - if true
-#             .product__caution
-#               この商品はゆうゆうメルカリ便を利用しているため、アプリからのみ購入できます。
-#           =link_to "購入する", root_path, class: "btn"
-#           - if true
-#             .product__appNavi
-#               .product__appNavi__caution
-#               アプリをお持ちでない方は以下よりインストールしてご利用いただけます
-#               .product__appNavi__link
-#                 =link_to image_tag("https://www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?1855818912", class: "product__appNavi__icon"), "https://itunes.apple.com/jp/app/id667861049?l=ja&mt=8", class: "opa"
-#                 =link_to image_tag("https://www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?1855818912", class: "product__appNavi__icon"), "https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja", class: "opa"             
-#       .address
-#         .address__top 配送先
-#         .address__postalCode 〒000-1107
-#         .address__detail XXXXXXXXXXXX
-#         .address__name 山田　太郎
-#         =link_to "変更する >", "#住所変更画面へ", class: "opa change"
-#       .termsOfPayment
-#         .termsOfPayment__top 支払い方法
-#         .termsOfPayment__cardNo ********1107
-#         .termsOfPayment__expirationDate 02/22
-#         %div
-#           =image_tag("https://www-mercari-jp.akamaized.net/assets/img/card/visa.svg?1855818912", class: "termsOfPayment__icon")
-#         =link_to "変更する >", "#カード変更画面へ", class: "opa change"

-#     %footer.footer
-#       %ul.footer__link.opa
-#         %li
-#           =link_to "プライバシーポリシー", "#プライバシー", class: "footer__link__span"
-#         %li.footer__link__a
-#           =link_to "メルカリ利用規約", "#メルカリ利用規約", class: "footer__link__span"
-#         %li.footer__link__a
-#           =link_to "特定商取引に関する表記", "#特定商取引に関する表記", class: "footer__link__span"
-#       .footer__mercari
-#         .footer__mercari__logo
-#           =link_to image_tag("https://www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?1855818912", class: "footer__mercari__logo__icon"), "#topへ移動", class: "opa"
-#         %small.footer__mercari__logo__c ©️ Mercari, Inc.
.detailWrapper
  = render './shareParts/detailHeader'
  .detailMain
    .Top
      %h2.purchaseTop 購入内容の確認
    .purchaseDetail
      .purchaseDetail__info
        - @product_image.each do |img|
          = image_tag img.image_url.to_s
        .purchaseDetail__info__name
          = @product.name
      .purchaseDetail__price
        .purchaseDetail__price--left ¥#{@product.price}
        .purchaseDetail__price--right 送料込み
      .point.btn ポイントはありません
      .purchaseDetail__payment
        .purchaseDetail__payment--left 支払い金額
        .purchaseDetail__payment--right ¥#{@product.price}
      - if true
        .purchaseDetail__caution
          この商品はゆうゆうメルカリ便を利用しているため、アプリからのみ購入できます。
      = form_with(model: @product, local: true, url: pay_product_path, method: :post, class: "detailMain") do |f|
        = f.submit class: "btn", value: "購入する"
      - if true
        .purchaseDetail__appNavi
          .purchaseDetail__appNavi__caution
          アプリをお持ちでない方は以下よりインストールしてご利用いただけます
          .purchaseDetail__appNavi__link
            =link_to image_tag("https://www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?1855818912", class: "purchaseDetail__appNavi__icon"), "https://itunes.apple.com/jp/app/id667861049?l=ja&mt=8", class: "opa"
            =link_to image_tag("https://www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?1855818912", class: "purchaseDetail__appNavi__icon"), "https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja", class: "opa"             
    .purchaseShippingAddress
      .purchaseShippingAddress__top 配送先
      .purchaseShippingAddress__postalCode 〒000-1107
      .purchaseShippingAddress__detail XXXXXXXXXXXX
      .purchaseShippingAddress__name
        = current_user.nickname
      = link_to "変更する >", "#住所変更画面へ", class: "opa change"
    .purchaseTermsOfPayment
      .purchaseTermsOfPayment__top 支払い方法
      .purchaseTermsOfPayment__cardNo
        = "**** **** **** " + @default_card_information.last4
      .purchaseTermsOfPayment__expirationDate
        - exp_month = @default_card_information.exp_month.to_s
        - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
        = exp_month + " / " + exp_year
      %div
        = image_tag("https://www-mercari-jp.akamaized.net/assets/img/card/visa.svg?1855818912", class: "purchaseTermsOfPayment__icon")
      =link_to "変更する >", "credit_card", class: "opa change"
  = render '/shareParts/detailFooter'

app/views/products/show.html.haml
.headers
  = render partial: "top/header"
-# %header.pc-header.visible-pc.with-shadow
-#   .pc-header-inner
-#     .pc-header-top
-#       %div
-#         = link_to root_path do
-#           -# = image_tag "https://web-jp-assets.mercdn.net/_next/static/images/logo-acdd90ac4f472d5a6f7a330d33ab1225.svg", size: "134x36", alt: "mercari"
-#       %form.pc-header-form{action: "検索URL"}
-#         %input.input-default{name: "keyword", placeholder: "何かお探しですか？", type: "search", value: ""}/
-#         %i.icon-search
-#     .pc-header-nav-box.clearfix
-#       %nav.l-left
-#         %ul.pc-header-nav
-#           %li
-#             %h2
-#               = link_to "カテゴリーURL", class: "pc-header-nav-root list-parent" do
-#                 %i.icon-list.pc-header-cat-brand-icon
-#                 %span カテゴリーから探す
-#             /
-#               <ul class="pc-header-nav-parent-wrap" data-mega="1" style="width: auto;">
-#               <li class="pc-header-nav-parent">
-#               <h3>
-#               <a href="カテゴリーURL">カテゴリー名</a>
-#               </h3>
-#               <ul class="pc-header-nav-child-wrap" data-mega="2">
-#               <li class="pc-jeader-nav-child">
-#               <a href="カテゴリーURL">カテゴリー名</a>
-#               </li>
-#               </ul>
-#               </li>
-#               </ul>  今後実装していくが今は保留にしておきます
-#           %li
-#             %h2
-#               = link_to "ブランドURL", class: "pc-header-nav-root list-parent" do
-#                 %i.icon-tag.pc-header-cat-brand-icon
-#                 %span ブランドから探す
-#       .l-right
-#         %ul.pc-header-login-nav
-#           %li
-#             = link_to "新規会員登録",new_user_registration_path, class: "sp-header-btn btn-red"
-#           %li
-#             = link_to "ログイン",user_session_path, class: "sp-header-btn header-login"
%section.product_detail.l-single-container
  %h1.product_name
    = @product.name
  %p.product_wording
    『
    = @product.name
    』は、'X'回の取引実績を持つ
    = @user.nickname
    さんから出品されました。
    = @product.brand
    の商品で、
    = @product.address.name
    から
    = @product.period.period
    されます。
  .product_main_content.claarfix
    .item_image
      .owl-carousel.owl-loaded.owl-drag
        .owl-stage-outer
          .owl-stage{style: "width: 900px;"}
            .owl-item{style: "width: 300px;"}
              -num = 0
              .owl-item-inner
                - @product.product_images.each do |img|
                  = image_tag img.image_url.to_s, class: "big_image"
                  -break if num== 0
        .owl-nav.disabled
          .owl-prev prev
          .owl-next next
        .owl-dots
          -num = 0
          - @product.product_images.each do |img|
            -if num == 0
              -num += 1
            -else
              .owl-dot
                %span
                  = image_tag img.image_url.to_s, class: "small_image"
              -num += 1
          .owl-dot-inner
      -if @product.purchase_status == "2"
        .item-sold-out-badge
          %div SOLD
      -else
    .item-prige-box.text-center.visible-sp
      %span.item-price.bold ¥X,XXX
      %span.item-tax (税込)
      %span.item-shipping-fee 送料込み
    %section.visible-sp
      .item-btn-float-area
        = link_to "購入画面に進む", "購入画面URL", class: "item-buy-btn"
    %table.item-detail-table
      %tbody
        %tr
          %th 出品者
          %td
            = link_to "ユーザーページURL" do
              = @user.nickname
            %div
              .item-user-ratings
                %i.icon-good
                %span
                  00
              .item-user-ratings
                %i.icon-normal
                %span
                  00
              .item-user-ratings
                %i.icon-bad
                %span
                  00
        %tr
          %th カテゴリー
          %td
            = link_to "カテゴリーURL" do
              %div 
                -if !(@category.ancestry == nil) and !(@category.parent.ancestry == nil)
                  = @category.parent.parent.name
                -else
                -if !(@category.ancestry == nil)
                  = @category.parent.name
                -else
                = @category.name
        %tr
          %th ブランド
          %td
            = link_to "ブランドURL" do
              %div 
              = @product.brand
        -if !(@product.size_id == nil)
          %tr
            %th サイズ
            %td
              = link_to "ブランドURL" do
                %div 
                = @product.size.size
        -else
        %tr
          %th 商品の状態
          %td 
            = @product.status.status
        %tr
          %th 配送料の負担
          %td
            = @charge_method.layer
        -if !(@product.sendmethod_id == nil)
          %tr
            %th 配送の方法
            %td
              = @charge_method2.layer
        -else
        %tr
          %th 配送元の地域
          %td
            = link_to "都道府県URL" do
              = @product.address.name
        %tr
          %th 発送日の目安
          %td
            = @product.period.period
  .item-price-box.text-center
    %span.item-price.bold
      = "¥#{@product.price.to_s(:delimited)}"
    %span.item-tax (税込)
    %span.item-shipping-fee
      = @product.shipping_fee
  -if user_signed_in? && current_user.id == @user.id
  -else
    -if @product.purchase_status == "2"
      .item-buy-btn.disabled
        売り切れました
    -else
      = link_to "購入画面に進む", purchase_product_path, class: "item-buy-btn"
  .item-description.f14
    %p.item-description-inner
      = @product.description
  .item-button-container.clearfix
    .item-button-left
      = link_to "いいねURL", class: "item-button item-button-like" do
        %i.icon-like-border
        %span いいね！
        %span{"data-num": "like"}
          X
      = link_to "通報フォームURL", class: "item-button item-button-report clearfix" do
        %i.icon-flag
        %span 不適切な商品の報告
    .item-button-right
      = link_to "安心安全への取り組みURL", target: "_blank" do
        %i.icon-lock
        %span あんしん・あんぜんへの取り組み
-if user_signed_in? && current_user.id == @user.id
  .x-single-container
    .listing-item-change-box
      = link_to edit_product_path, class: "btn-default btn-red" do
        %span 商品の編集
      %p.text-center
        %span or
      %form{action: "URL", method: "POST", novalidate: "novalidate"}
        %input{name: "__csrf_value", type: "hidden", value: "何かの文字列"}
        %button{type: "submit", class: "btn-default btn-gray"}
          %span 出品を一旦停止する
      %button{"data-modal": "delete-item", "data-open": "modal", class: "btn-default btn-gray"}
        = link_to 'この商品を削除する', product_path, class: "white-link", method: :delete
-else
.item-detail-message
  .message-container
    .message-content
      %ul.message-items
        %li.clearfix
          = link_to "ユーザーページURL", class: "message-user" do
            %figure
              %div
                = image_tag root_path, alt: ""
              %figcaption.bold
                ユーザー名
          .message-body
            .message-body-text
              "コメント内容"
              %br/
              "コメント内容二行目"
            .message-icons.clearfix
              %time.message-icon-left
                %i.icon-time
                %span XX日前
              .message-icon-right
                %form{action: "コメント通報ページURL", method: "POST"}
                  %button{type: "submit", class: "small-btn"}
                    %i.icon-flag
                  %input{name: "redirect_url_key", type: "hidden", value: "item_detail"}/
            %i.icon-balloon
    .message-content
      = render 'comments/comment'
    %aside.modal{"data-close": "modat", "data-modal": "delete-comment"}
      .modal-inner.modal-banner
        .modal-body
          .modal-head.bold 確認
          %div{"data-comment": "body"}
          = succeed "\"\u{672c}\u{5f53}\u{306b}\u{3053}\u{306e}\u{30b3}\u{30e1}\u{30f3}\u{30c8}\u{3092}\u{524a}\u{9664}\u{3057}\u{3066}\u{3088}\u{308d}\u{3057}\u{3044}\u{3067}\u{3059}\u{304b}\u{ff1f}\"" do
            %br/
        %form{action: "URL"}
          .clearfix
            .modal-btn.modal-btn-cancel{"data-close": "modal"} キャンセル
            %button.modal-btn.modal-btn-submit{type: "submit"}
              削除する
          %input{name: "item_id", type: "hidden", value: "商品ID"}/
          %input{name: "comment_id", type: "hidden", value: ""}/
          %input{name: "redirect_url_key", type: "hidden", value: "item_detail"}/
          %input{name: "__csrf_value", type: "hidden", value: "何か"}/
%ul.nav-item-link-prev-next.clearfix
  -if !(@product.previous == nil)
    %li.nav-item-link-prev
      = link_to "/products/#{@product.previous.id}" do
        %i.icon-arrow-left
        = @product.previous.name
  -else
  -if !(@product.next == nil)
    %li.nav-item-link-next
      = link_to "/products/#{@product.next.id}" do
        = @product.next.name
        %i.icon-arrow-right
  -else
.item-social-media-box
  .text-center
    .fb-save.fb_iframe_widget{"data-uri": "何かのURL?", "fb-iframe-plugin-query": "何かのURL", "fb-xfbml-state": "rendered"}
      %span{style: "vertical-align: top; width: 0px; height: 0px; overflow:hidden;"}
        %iframe{allow: "encrypted-media", allowfullscreen: "true", allowtransparency: "true", frameborder: "0", height: "1000px", name: "商品id?", scrolling: "no", src: "facebookURL", style: "border: none; visibility: visible; width: 0px; height: 0px;", title: "fb: save Facebook Social Plugin", width: "1000px"}
  %ul.social-media-box
    %li
      = link_to "facebookURL", class: "share-btn", target: "_blank" do
        %i.icon-facebook
    %li
      = link_to "twitterURL", class: "share-btn", target: "_blank" do
        %i.icon-twitter
    %li.social-hidden-item
      = link_to "lineURL", class: "share-btn", target: "_blank" do
        %i.icon-line
    %li
      = link_to "pinterestURL", class: "share-btn", target: "_blank" do
        %i.icon-pinterest
.items-in-user-profile
  %section.item-box-container.clearfix.related-item-column.items-in-user-profile
    %h2.items-box-head
      = link_to "URL" do
        = @user.nickname 
        さんのその他の出品
    .items-box-set
      -num = 0
      -@product_user_other.each do |product|
        .items-box-content.clearfix
          %section.items-box
            = link_to "/products/#{product.id}" do
              %figure.items-box-photo.__web-inspector-hide-shortcut__
                = image_tag @product_user_other_image[num].image_url.to_s, class: "lazyloaded", alt: ""
                -if product.purchase_status == "2"
                  .item-sold-out-badge-small
                    %div SOLD
                -else
              .items-box-body
                %h3.items-box-name.font-2
                  = product.name
                .items-box-num
                  .items-box-price.font-5 
                    = "¥#{product.price.to_s(:delimited)}"
                  .font-2
                    %i.icon-like-border
                    %span
                      X
        -num += 1
        -break if num== 6
  %section.items-box-container.clearfix.related-item-column
    %h2.items-box-head
      = link_to "カテゴリーURL" do
        = @category.name
        その他の商品
    .items-box-set
      -num = 0
      -@category_same.each do |category|
        .items-box-content.clearfix
          %section.items-box
            = link_to "/products/#{category.id}" do
              %figure.items-box-photo
                = image_tag @other_product_image[num].image_url.to_s, class: "lazyloaded", alt: ""
                -if category.purchase_status == "2"
                  .item-sold-out-badge-small
                    %div SOLD
                -else
              .items-box-body
                %h3.items-box-name.font-2
                  = category.name
                .items-box-num
                  .items-box-price.font-5
                    = "¥#{category.price.to_s(:delimited)}"
                  .font-2
                    %i.icon-like-border
                    %span
                      X
        -num += 1
        -break if num== 6
%aside.modal{"data-close": "modal", "data-modal": "report-item"}
  .modal-inner.modal-banner
    .modal-body
      .modal-head.bold 確認
      "不適切な商品を報告しますか？"
    .clearfix
      .modal-btn.modal-btn-cancel{"data-close": "modal"} キャンセル
      = link_to "URL" do
        %button.modal-btn.modal-btn-submit はい
- breadcrumb :product
= render "layouts/breadcrumbs"
%aside.download-bar
  = render partial: "top/download-bar"
%footer.footer
  = render partial: "top/footer"